// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeAhPDPBaBivogyb4y_Yr5M-rrh17tnEg',
    appId: '1:643665166344:web:3c02101d68ba74e43d91bd',
    messagingSenderId: '643665166344',
    projectId: 'reverb-music-streaming',
    authDomain: 'reverb-music-streaming.firebaseapp.com',
    storageBucket: 'reverb-music-streaming.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8-zm-TQk5YWxlzlj8P_ZfnJOPj-k5Z5s',
    appId: '1:643665166344:android:802f9eb6d60820f93d91bd',
    messagingSenderId: '643665166344',
    projectId: 'reverb-music-streaming',
    storageBucket: 'reverb-music-streaming.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbMXRAlEq-HnTCLrde1O2SkFR38jonic',
    appId: '1:643665166344:ios:fb94a62c69310f8c3d91bd',
    messagingSenderId: '643665166344',
    projectId: 'reverb-music-streaming',
    storageBucket: 'reverb-music-streaming.appspot.com',
    iosClientId: '643665166344-m1tci7nfqvd3s8s2oqkjk1cm0tdcgq35.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbMXRAlEq-HnTCLrde1O2SkFR38jonic',
    appId: '1:643665166344:ios:fb94a62c69310f8c3d91bd',
    messagingSenderId: '643665166344',
    projectId: 'reverb-music-streaming',
    storageBucket: 'reverb-music-streaming.appspot.com',
    iosClientId: '643665166344-m1tci7nfqvd3s8s2oqkjk1cm0tdcgq35.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjects',
  );
}
